//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocGenerator.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClickLink {
            get {
                object obj = ResourceManager.GetObject("ClickLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClickLink.png.
        /// </summary>
        internal static string ClickLinkEmbededFileName {
            get {
                return ResourceManager.GetString("ClickLinkEmbededFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocGenerator.ClickLink.png.
        /// </summary>
        internal static string ClickLinkImageURL {
            get {
                return ResourceManager.GetString("ClickLinkImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11000.
        /// </summary>
        internal static string DefaultTableWidth {
            get {
                return ResourceManager.GetString("DefaultTableWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /displayifs.aspx?ID=.
        /// </summary>
        internal static string DisplayFormURI {
            get {
                return ResourceManager.GetString("DisplayFormURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /editifs.aspx?ID=.
        /// </summary>
        internal static string EditFormURI {
            get {
                return ResourceManager.GetString("EditFormURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF0000.
        /// </summary>
        internal static string ErrorTextColor {
            get {
                return ResourceManager.GetString("ErrorTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teams.dimensiondata.com/sites/ServiceCatalogue/SiteCollectionImages/ContentImages/ImagePlaceholder.png.
        /// </summary>
        internal static string ImagePlaceholderURL {
            get {
                return ResourceManager.GetString("ImagePlaceholderURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8064A2.
        /// </summary>
        internal static string Layer1Color {
            get {
                return ResourceManager.GetString("Layer1Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4F81BD.
        /// </summary>
        internal static string Layer2Color {
            get {
                return ResourceManager.GetString("Layer2Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F79646.
        /// </summary>
        internal static string Layer3Color {
            get {
                return ResourceManager.GetString("Layer3Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocGenerator\Documents\.
        /// </summary>
        internal static string LocalDocumentPath {
            get {
                return ResourceManager.GetString("LocalDocumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocGenerator\Images\.
        /// </summary>
        internal static string LocalImagePath {
            get {
                return ResourceManager.GetString("LocalImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocGenerator\Templates\.
        /// </summary>
        internal static string LocalTemplatePath {
            get {
                return ResourceManager.GetString("LocalTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_vti_bin/listdata.svc.
        /// </summary>
        internal static string SharePointRESTuri {
            get {
                return ResourceManager.GetString("SharePointRESTuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teams.dimensiondata.com/sites/servicecatalogue.
        /// </summary>
        internal static string SharePointSiteURL {
            get {
                return ResourceManager.GetString("SharePointSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teams.dimensiondata.com.
        /// </summary>
        internal static string SharePointURL {
            get {
                return ResourceManager.GetString("SharePointURL", resourceCulture);
            }
        }
    }
}
