//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DocGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DocGenerator.Properties.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ClickLink {
            get {
                object obj = ResourceManager.GetObject("ClickLink", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClickLink.png.
        /// </summary>
        internal static string ClickLinkFileName {
            get {
                return ResourceManager.GetString("ClickLinkFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resources\ClickLink.png.
        /// </summary>
        internal static string ClickLinkImageURL {
            get {
                return ResourceManager.GetString("ClickLinkImageURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 16838.
        /// </summary>
        internal static string DefaultPageHeight {
            get {
                return ResourceManager.GetString("DefaultPageHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11906.
        /// </summary>
        internal static string DefaultPageWidth {
            get {
                return ResourceManager.GetString("DefaultPageWidth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /displayifs.aspx?ID=.
        /// </summary>
        internal static string DisplayFormURI {
            get {
                return ResourceManager.GetString("DisplayFormURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document Acceptance.
        /// </summary>
        internal static string Document_AcceptanceText {
            get {
                return ResourceManager.GetString("Document_AcceptanceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acronyms.
        /// </summary>
        internal static string Document_Acronyms_HeadingText {
            get {
                return ResourceManager.GetString("Document_Acronyms_HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activities:.
        /// </summary>
        internal static string Document_Activities_Heading {
            get {
                return ResourceManager.GetString("Document_Activities_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumptions:.
        /// </summary>
        internal static string Document_ActivityTable_RowTitle_Assumptions {
            get {
                return ResourceManager.GetString("Document_ActivityTable_RowTitle_Assumptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activity Description:.
        /// </summary>
        internal static string Document_ActivityTable_RowTitle_Description {
            get {
                return ResourceManager.GetString("Document_ActivityTable_RowTitle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs:.
        /// </summary>
        internal static string Document_ActivityTable_RowTitle_Inputs {
            get {
                return ResourceManager.GetString("Document_ActivityTable_RowTitle_Inputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Optionality:.
        /// </summary>
        internal static string Document_ActivityTable_RowTitle_Optionality {
            get {
                return ResourceManager.GetString("Document_ActivityTable_RowTitle_Optionality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs:.
        /// </summary>
        internal static string Document_ActivityTable_RowTitle_Outputs {
            get {
                return ResourceManager.GetString("Document_ActivityTable_RowTitle_Outputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image .
        /// </summary>
        internal static string Document_Caption_Image_Text {
            get {
                return ResourceManager.GetString("Document_Caption_Image_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table .
        /// </summary>
        internal static string Document_Caption_Table_Text {
            get {
                return ResourceManager.GetString("Document_Caption_Table_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend to the colours:.
        /// </summary>
        internal static string Document_ColourCodingLedgend_Heading {
            get {
                return ResourceManager.GetString("Document_ColourCodingLedgend_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer 1 content will be reflected in this colour..
        /// </summary>
        internal static string Document_ColourCodingLedgend_Layer1 {
            get {
                return ResourceManager.GetString("Document_ColourCodingLedgend_Layer1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer 2 content will be reflected in this colour..
        /// </summary>
        internal static string Document_ColourCodingLedgend_Layer2 {
            get {
                return ResourceManager.GetString("Document_ColourCodingLedgend_Layer2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layer 3 content will be reflected in this colour..
        /// </summary>
        internal static string Document_ColourCodingLedgend_Layer3 {
            get {
                return ResourceManager.GetString("Document_ColourCodingLedgend_Layer3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This document contains text of various colours. The following colours means that the content are constructed based on the following content layers:.
        /// </summary>
        internal static string Document_ColourCodingLedgend_Text {
            get {
                return ResourceManager.GetString("Document_ColourCodingLedgend_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client&apos;s Responsibilities:.
        /// </summary>
        internal static string Document_DeliverableClientResponsibilities_Heading_Text {
            get {
                return ResourceManager.GetString("Document_DeliverableClientResponsibilities_Heading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dimension Data&apos;s Obligations:.
        /// </summary>
        internal static string Document_DeliverableDDsObligations_Heading_Text {
            get {
                return ResourceManager.GetString("Document_DeliverableDDsObligations_Heading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exclusions:.
        /// </summary>
        internal static string Document_DeliverableExclusions_Heading_Text {
            get {
                return ResourceManager.GetString("Document_DeliverableExclusions_Heading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governance Controls:.
        /// </summary>
        internal static string Document_DeliverableGovernanceControls_Heading_Text {
            get {
                return ResourceManager.GetString("Document_DeliverableGovernanceControls_Heading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inputs:.
        /// </summary>
        internal static string Document_DeliverableInputs_Heading_Text {
            get {
                return ResourceManager.GetString("Document_DeliverableInputs_Heading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outputs:.
        /// </summary>
        internal static string Document_DeliverableOutputs_Heading_Text {
            get {
                return ResourceManager.GetString("Document_DeliverableOutputs_Heading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverables, Reports and Meetings:.
        /// </summary>
        internal static string Document_DeliverableReportsMeetings_Heading {
            get {
                return ResourceManager.GetString("Document_DeliverableReportsMeetings_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverables:.
        /// </summary>
        internal static string Document_Deliverables_Heading_Text {
            get {
                return ResourceManager.GetString("Document_Deliverables_Heading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here .
        /// </summary>
        internal static string Document_DRM_ClickHere {
            get {
                return ResourceManager.GetString("Document_DRM_ClickHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  to navigate to the relevant detailed description in the Deliverable, Reports and Meetings section below..
        /// </summary>
        internal static string Document_DRM_Navigate_To_Detail {
            get {
                return ResourceManager.GetString("Document_DRM_Navigate_To_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverables, Reports, Meetings.
        /// </summary>
        internal static string Document_DRM_Section_Text {
            get {
                return ResourceManager.GetString("Document_DRM_Section_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Key Advantages.
        /// </summary>
        internal static string Document_Element_ClientKeyAdvantages {
            get {
                return ResourceManager.GetString("Document_Element_ClientKeyAdvantages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Key Benefits.
        /// </summary>
        internal static string Document_Element_ClientKeyBenefits {
            get {
                return ResourceManager.GetString("Document_Element_ClientKeyBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Critical Success Factors.
        /// </summary>
        internal static string Document_Element_CriticalSuccessFactors {
            get {
                return ResourceManager.GetString("Document_Element_CriticalSuccessFactors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High Level Process.
        /// </summary>
        internal static string Document_Element_HighLevelProcess {
            get {
                return ResourceManager.GetString("Document_Element_HighLevelProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Dimension Data Benefits.
        /// </summary>
        internal static string Document_Element_KeyDDBenefits {
            get {
                return ResourceManager.GetString("Document_Element_KeyDDBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Performance Indicators.
        /// </summary>
        internal static string Document_Element_KPI {
            get {
                return ResourceManager.GetString("Document_Element_KPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Objectives.
        /// </summary>
        internal static string Document_Element_Objectives {
            get {
                return ResourceManager.GetString("Document_Element_Objectives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executive Summary.
        /// </summary>
        internal static string Document_ExecutiveSummary_HeadingText {
            get {
                return ResourceManager.GetString("Document_ExecutiveSummary_HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glossary of Terms and Acronyms.
        /// </summary>
        internal static string Document_GlossaryAndAcronymSection_HeadingText {
            get {
                return ResourceManager.GetString("Document_GlossaryAndAcronymSection_HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 761365.
        /// </summary>
        internal static string Document_Image_Left_Indent {
            get {
                return ResourceManager.GetString("Document_Image_Left_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introduction.
        /// </summary>
        internal static string Document_Introduction_HeadingText {
            get {
                return ResourceManager.GetString("Document_Introduction_HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Introductory.
        /// </summary>
        internal static string Document_IntruductorySection_HeadingText {
            get {
                return ResourceManager.GetString("Document_IntruductorySection_HeadingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meetings:.
        /// </summary>
        internal static string Document_Meetings_Heading_Text {
            get {
                return ResourceManager.GetString("Document_Meetings_Heading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Key Benefits.
        /// </summary>
        internal static string Document_Product_ClientKeyBenefits {
            get {
                return ResourceManager.GetString("Document_Product_ClientKeyBenefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Key Dimension Data Benefits.
        /// </summary>
        internal static string Document_Product_KeyDD_Benefits {
            get {
                return ResourceManager.GetString("Document_Product_KeyDD_Benefits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports:.
        /// </summary>
        internal static string Document_Reports_Heading_Text {
            get {
                return ResourceManager.GetString("Document_Reports_Heading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumptions: .
        /// </summary>
        internal static string Document_RequirementMapping_AssumptionsHeading {
            get {
                return ResourceManager.GetString("Document_RequirementMapping_AssumptionsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compliance with Requirement: .
        /// </summary>
        internal static string Document_RequirementsMapping_ComplianceStatusTitle {
            get {
                return ResourceManager.GetString("Document_RequirementsMapping_ComplianceStatusTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverables,Reports and Meetings:.
        /// </summary>
        internal static string Document_RequirementsMapping_DeliverableReportMeetingsHeading {
            get {
                return ResourceManager.GetString("Document_RequirementsMapping_DeliverableReportMeetingsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source Reference: .
        /// </summary>
        internal static string Document_RequirementsMapping_ReferenceSourceTitle {
            get {
                return ResourceManager.GetString("Document_RequirementsMapping_ReferenceSourceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks: .
        /// </summary>
        internal static string Document_RequirementsMapping_RisksHeading {
            get {
                return ResourceManager.GetString("Document_RequirementsMapping_RisksHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure:.
        /// </summary>
        internal static string Document_RequirementsMapping_RiskTable_RiskExposure {
            get {
                return ResourceManager.GetString("Document_RequirementsMapping_RiskTable_RiskExposure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exposure value:.
        /// </summary>
        internal static string Document_RequirementsMapping_RiskTable_RiskExposureValue {
            get {
                return ResourceManager.GetString("Document_RequirementsMapping_RiskTable_RiskExposureValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mitigation:.
        /// </summary>
        internal static string Document_RequirementsMapping_RiskTable_RiskMitigation {
            get {
                return ResourceManager.GetString("Document_RequirementsMapping_RiskTable_RiskMitigation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk Statement:.
        /// </summary>
        internal static string Document_RequirementsMapping_RiskTable_RiskStatement {
            get {
                return ResourceManager.GetString("Document_RequirementsMapping_RiskTable_RiskStatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client Requirements.
        /// </summary>
        internal static string Document_RequirementsMapping_SectionHeading {
            get {
                return ResourceManager.GetString("Document_RequirementsMapping_SectionHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Level(s):.
        /// </summary>
        internal static string Document_RequirementsMapping_ServiceLevelsHeading {
            get {
                return ResourceManager.GetString("Document_RequirementsMapping_ServiceLevelsHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Levels:.
        /// </summary>
        internal static string Document_ServiceLevel_Section_Text {
            get {
                return ResourceManager.GetString("Document_ServiceLevel_Section_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Levels:.
        /// </summary>
        internal static string Document_ServiceLevels_Heading_Text {
            get {
                return ResourceManager.GetString("Document_ServiceLevels_Heading_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Formula:.
        /// </summary>
        internal static string Document_SLtable_RowCalculationFormula_Title {
            get {
                return ResourceManager.GetString("Document_SLtable_RowCalculationFormula_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation Method:.
        /// </summary>
        internal static string Document_SLtable_RowCalculationMethod_Title {
            get {
                return ResourceManager.GetString("Document_SLtable_RowCalculationMethod_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Level Conditions:.
        /// </summary>
        internal static string Document_SLtable_RowConditions_Title {
            get {
                return ResourceManager.GetString("Document_SLtable_RowConditions_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement:.
        /// </summary>
        internal static string Document_SLtable_RowMeasurement_Title {
            get {
                return ResourceManager.GetString("Document_SLtable_RowMeasurement_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measurement Interval:.
        /// </summary>
        internal static string Document_SLtable_RowMeasurementInterval_Title {
            get {
                return ResourceManager.GetString("Document_SLtable_RowMeasurementInterval_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reporting Interval:.
        /// </summary>
        internal static string Document_SLtable_RowReportingInterval_Title {
            get {
                return ResourceManager.GetString("Document_SLtable_RowReportingInterval_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applicable Service Hours:.
        /// </summary>
        internal static string Document_SLtable_RowServiceHours_Title {
            get {
                return ResourceManager.GetString("Document_SLtable_RowServiceHours_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Level Targets:.
        /// </summary>
        internal static string Document_SLtable_RowTargets_Title {
            get {
                return ResourceManager.GetString("Document_SLtable_RowTargets_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Level Thresholds:.
        /// </summary>
        internal static string Document_SLtable_RowThresholds_Title {
            get {
                return ResourceManager.GetString("Document_SLtable_RowThresholds_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not specified..
        /// </summary>
        internal static string Document_SLtable_ValueNotSpecified_Text {
            get {
                return ResourceManager.GetString("Document_SLtable_ValueNotSpecified_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1100.
        /// </summary>
        internal static string Document_Table_Left_Indent {
            get {
                return ResourceManager.GetString("Document_Table_Left_Indent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term.
        /// </summary>
        internal static string Document_TableColumn_GlossaryAcronyms_Column1_Heading {
            get {
                return ResourceManager.GetString("Document_TableColumn_GlossaryAcronyms_Column1_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acronym.
        /// </summary>
        internal static string Document_TableColumn_GlossaryAcronyms_Column2_Heading {
            get {
                return ResourceManager.GetString("Document_TableColumn_GlossaryAcronyms_Column2_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meaning.
        /// </summary>
        internal static string Document_TableColumn_GlossaryAcronyms_Column3_Heading {
            get {
                return ResourceManager.GetString("Document_TableColumn_GlossaryAcronyms_Column3_Heading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /editifs.aspx?ID=.
        /// </summary>
        internal static string EditFormURI {
            get {
                return ResourceManager.GetString("EditFormURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 360000.
        /// </summary>
        internal static string EMUperCM {
            get {
                return ResourceManager.GetString("EMUperCM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 914400.
        /// </summary>
        internal static string EMUperINCH {
            get {
                return ResourceManager.GetString("EMUperINCH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FF0000.
        /// </summary>
        internal static string ErrorTextColor {
            get {
                return ResourceManager.GetString("ErrorTextColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teams.dimensiondata.com/sites/ServiceCatalogue/SiteCollectionImages/ContentImages/ImagePlaceholder.png.
        /// </summary>
        internal static string ImagePlaceholderURL {
            get {
                return ResourceManager.GetString("ImagePlaceholderURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4F81BD.
        /// </summary>
        internal static string Layer1Color {
            get {
                return ResourceManager.GetString("Layer1Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F79646.
        /// </summary>
        internal static string Layer2Color {
            get {
                return ResourceManager.GetString("Layer2Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8064A2.
        /// </summary>
        internal static string Layer3Color {
            get {
                return ResourceManager.GetString("Layer3Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Activities/Activities.
        /// </summary>
        internal static string List_ActvitiesURI {
            get {
                return ResourceManager.GetString("List_ActvitiesURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Deliverable%20Activities/Deliverable%20Activities.
        /// </summary>
        internal static string List_DeliverableActivitiesURI {
            get {
                return ResourceManager.GetString("List_DeliverableActivitiesURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Deliverable%20Countries/Deliverable%20Countries.
        /// </summary>
        internal static string List_DeliverableCountriesURI {
            get {
                return ResourceManager.GetString("List_DeliverableCountriesURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Deliverable%20Service%20Levels/Deliverable%20Service%20Levels.
        /// </summary>
        internal static string List_DeliverableServiceLevelsURI {
            get {
                return ResourceManager.GetString("List_DeliverableServiceLevelsURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Deliverables/Deliverables.
        /// </summary>
        internal static string List_DeliverablesURI {
            get {
                return ResourceManager.GetString("List_DeliverablesURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Deliverable%20Activities/Deliverable%20Activities.
        /// </summary>
        internal static string List_DeliverableTechnologiesURI {
            get {
                return ResourceManager.GetString("List_DeliverableTechnologiesURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Document%20Collection%20Library/Document%20Collection.
        /// </summary>
        internal static string List_DocumentCollectionLibraryURI {
            get {
                return ResourceManager.GetString("List_DocumentCollectionLibraryURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Element%20Deliverables/Element%20Deliverables.
        /// </summary>
        internal static string List_ElementDeliverablesURI {
            get {
                return ResourceManager.GetString("List_ElementDeliverablesURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Feature%20Deliverables/Feature%20Deliverables.
        /// </summary>
        internal static string List_FeatureDeliverablesURI {
            get {
                return ResourceManager.GetString("List_FeatureDeliverablesURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Mapping%20Assumptions/Mapping%20Assumptions.
        /// </summary>
        internal static string List_MappingAssumptions {
            get {
                return ResourceManager.GetString("List_MappingAssumptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Mapping%20Deliverables/Mapping%20Deliverables.
        /// </summary>
        internal static string List_MappingDeliverables {
            get {
                return ResourceManager.GetString("List_MappingDeliverables", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Mapping%20Requirements/Mapping%20Requirements.
        /// </summary>
        internal static string List_MappingRequirements {
            get {
                return ResourceManager.GetString("List_MappingRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Mapping%20Risks/Mapping%20Risks.
        /// </summary>
        internal static string List_MappingRisks {
            get {
                return ResourceManager.GetString("List_MappingRisks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Mappings/Mappings.
        /// </summary>
        internal static string List_Mappings {
            get {
                return ResourceManager.GetString("List_Mappings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Mapping%20Service%20Levels/Mapping%20Service%20Levels.
        /// </summary>
        internal static string List_MappingServiceLevels {
            get {
                return ResourceManager.GetString("List_MappingServiceLevels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Mapping%20Service%20Towers/Mapping%20Service%20Tower.
        /// </summary>
        internal static string List_MappingServiceTowers {
            get {
                return ResourceManager.GetString("List_MappingServiceTowers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/OLAs/OLAs.
        /// </summary>
        internal static string List_OLAsURI {
            get {
                return ResourceManager.GetString("List_OLAsURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Product%20Countries/Product%20Countries.
        /// </summary>
        internal static string List_ProductCountriesURI {
            get {
                return ResourceManager.GetString("List_ProductCountriesURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Service%20Elements/Service%20Elements.
        /// </summary>
        internal static string List_ServiceElementsURI {
            get {
                return ResourceManager.GetString("List_ServiceElementsURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Service%20Families/Service%20Families.
        /// </summary>
        internal static string List_ServiceFamiliesURI {
            get {
                return ResourceManager.GetString("List_ServiceFamiliesURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Service%20Features/Service%20Features.
        /// </summary>
        internal static string List_ServiceFeaturesURI {
            get {
                return ResourceManager.GetString("List_ServiceFeaturesURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Service%20Levels/Service%20Levels.
        /// </summary>
        internal static string List_ServiceLevelsURI {
            get {
                return ResourceManager.GetString("List_ServiceLevelsURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Service%20Portfolios/Service%20Portfolios.
        /// </summary>
        internal static string List_ServicePortfoliosURI {
            get {
                return ResourceManager.GetString("List_ServicePortfoliosURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Service%20Products/Service%20Products.
        /// </summary>
        internal static string List_ServiceProductsURI {
            get {
                return ResourceManager.GetString("List_ServiceProductsURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /sites/ServiceCatalogue/Lists/Technology%20Products/Technology%20Products.
        /// </summary>
        internal static string List_TechnologyProductsURI {
            get {
                return ResourceManager.GetString("List_TechnologyProductsURI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocGenerator\Documents\.
        /// </summary>
        internal static string LocalDocumentPath {
            get {
                return ResourceManager.GetString("LocalDocumentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocGenerator\Images\.
        /// </summary>
        internal static string LocalImagePath {
            get {
                return ResourceManager.GetString("LocalImagePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DocGenerator\Templates\.
        /// </summary>
        internal static string LocalTemplatePath {
            get {
                return ResourceManager.GetString("LocalTemplatePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /_vti_bin/listdata.svc.
        /// </summary>
        internal static string SharePointRESTuri {
            get {
                return ResourceManager.GetString("SharePointRESTuri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teams.dimensiondata.com/sites/servicecatalogue.
        /// </summary>
        internal static string SharePointSiteURL {
            get {
                return ResourceManager.GetString("SharePointSiteURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://teams.dimensiondata.com.
        /// </summary>
        internal static string SharePointURL {
            get {
                return ResourceManager.GetString("SharePointURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E:\DocGenerator\TestContent\.
        /// </summary>
        internal static string TestData_Location {
            get {
                return ResourceManager.GetString("TestData_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 81.
        /// </summary>
        internal static string Workbook_Comments_FontColor {
            get {
                return ResourceManager.GetString("Workbook_Comments_FontColor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tahoma.
        /// </summary>
        internal static string Workbook_Comments_RunFont {
            get {
                return ResourceManager.GetString("Workbook_Comments_RunFont", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string Workbook_CRM_Matrix_NewColumn_Text {
            get {
                return ResourceManager.GetString("Workbook_CRM_Matrix_NewColumn_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumption.
        /// </summary>
        internal static string Workbook_CRM_Matrix_RowType_Assumption {
            get {
                return ResourceManager.GetString("Workbook_CRM_Matrix_RowType_Assumption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deliverable.
        /// </summary>
        internal static string Workbook_CRM_Matrix_RowType_Deliverable {
            get {
                return ResourceManager.GetString("Workbook_CRM_Matrix_RowType_Deliverable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Requirement.
        /// </summary>
        internal static string Workbook_CRM_Matrix_RowType_Requirement {
            get {
                return ResourceManager.GetString("Workbook_CRM_Matrix_RowType_Requirement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risk.
        /// </summary>
        internal static string Workbook_CRM_Matrix_RowType_Risk {
            get {
                return ResourceManager.GetString("Workbook_CRM_Matrix_RowType_Risk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service Level.
        /// </summary>
        internal static string Workbook_CRM_Matrix_RowType_ServiceLevel {
            get {
                return ResourceManager.GetString("Workbook_CRM_Matrix_RowType_ServiceLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tower.
        /// </summary>
        internal static string Workbook_CRM_Matrix_RowType_TowerOfService {
            get {
                return ResourceManager.GetString("Workbook_CRM_Matrix_RowType_TowerOfService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assumptions.
        /// </summary>
        internal static string Workbook_CRM_Worksheet_Name_Assumptions {
            get {
                return ResourceManager.GetString("Workbook_CRM_Worksheet_Name_Assumptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Matrix.
        /// </summary>
        internal static string Workbook_CRM_Worksheet_Name_Matrix {
            get {
                return ResourceManager.GetString("Workbook_CRM_Worksheet_Name_Matrix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Risks.
        /// </summary>
        internal static string Workbook_CRM_Worksheet_Name_Risks {
            get {
                return ResourceManager.GetString("Workbook_CRM_Worksheet_Name_Risks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string Workbooks_Comments_FontFamily {
            get {
                return ResourceManager.GetString("Workbooks_Comments_FontFamily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string Workbooks_Comments_FontSize {
            get {
                return ResourceManager.GetString("Workbooks_Comments_FontSize", resourceCulture);
            }
        }
    }
}
